=== Azarta2Zygoto/profile/src/schemas/profile.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Profil",
    "type": "object",
    "properties": {
        "lastname": {
            "type": "string"
        },
        "firstname": {
            "type": "string"
        },
        "socials": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": ["linkedin", "github"]
                    },
                    "url": {
                        "type": "string",
                        "format": "uri"
                    }
                },
                "required": ["type", "url"],
                "additionalProperties": false
            }
        },
        "gmail": {
            "type": "string",
            "format": "email"
        },
        "job": {
            "type": "string"
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "nationality": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": ["lastname", "firstname"],
    "additionalProperties": false
}

=== Azarta2Zygoto/profile/src/data/profile-data.json
{
    "lastname": "Potiron",
    "firstname": "Quentin",
    "socials": [
        {
            "type": "linkedin",
            "url": "https://www.linkedin.com/in/quentin-potiron-424146309/"
        },
        {
            "type": "github",
            "url": "https://github.com/Azarta2Zygoto"
        }
    ],
    "gmail": "quentin.potiron@gmail.com",
    "job": "Centrale Lyon",
    "languages": ["fr", "en", "es"],
    "nationality": ["fr"]
}
